name: Echo Secret

on:
  push:
    branches:
      - master

jobs:
  echo_secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo SSH Private Key
        run: echo "SSH Private Key: ${{ secrets.SSH_PRIVATE_KEY }}"
