name: Echo Secret

on:
  workflow_dispatch:  # Manual trigger

jobs:
  echo_secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo vps_host
        run: 'echo "SSH Private Key: ${{ secrets.VPS_HOST }}"'